"""Initial schema: groups, users, settings, workflow tables, conversations

Revision ID: 4dcda9cfbcae
Revises: 
Create Date: 2026-04-15 19:45:02.200431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = '4dcda9cfbcae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_groups',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('group_name', sa.VARCHAR(), server_default=sa.text("'Undefined group'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text("'TRUE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index(op.f('ix_api_groups_deleted'), 'api_groups', ['deleted'], unique=False)
    op.create_table('api_settings',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('workflow_types',
    sa.Column('type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('type_desc', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('type_category', sa.VARCHAR(length=32), server_default=sa.text("'general'"), nullable=False),
    sa.Column('default_config', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('required_services', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text("'TRUE'"), nullable=False),
    sa.PrimaryKeyConstraint('type_id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('api_users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deleted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('group_id', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_groupadmin', sa.Boolean(), server_default=sa.text("'FALSE'"), nullable=False),
    sa.Column('is_manager', sa.Boolean(), server_default=sa.text("'FALSE'"), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.CheckConstraint("char_length(user_name) BETWEEN 3 AND 32 AND user_name ~ '^[a-z0-9_-]+$'", name='ck_api_users_user_name_format'),
    sa.ForeignKeyConstraint(['group_id'], ['api_groups.group_id'], name='fk_api_users_group_id'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_name'),
    sa.UniqueConstraint('user_name', name='uq_api_users_user_name')
    )
    op.create_index(op.f('ix_api_users_deleted'), 'api_users', ['deleted'], unique=False)
    op.create_index(op.f('ix_api_users_email'), 'api_users', ['email'], unique=True)
    op.create_table('group_settings',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['api_groups.group_id'], name='fk_group_settings_group_id'),
    sa.PrimaryKeyConstraint('group_id', 'name')
    )
    op.create_table('user_workflows',
    sa.Column('workflow_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('config', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text("'TRUE'"), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['api_groups.group_id'], name='fk_user_workflows_group_id'),
    sa.ForeignKeyConstraint(['type_id'], ['workflow_types.type_id'], name='fk_user_workflows_type_id'),
    sa.ForeignKeyConstraint(['user_id'], ['api_users.user_id'], name='fk_user_workflows_user_id'),
    sa.PrimaryKeyConstraint('workflow_id')
    )
    op.create_table('conversations',
    sa.Column('conversation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_type', sa.VARCHAR(length=20), server_default=sa.text("'query'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['api_users.user_id'], name='fk_conversations_user_id'),
    sa.ForeignKeyConstraint(['workflow_id'], ['user_workflows.workflow_id'], name='fk_conversations_workflow_id'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('workflow_runs',
    sa.Column('run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('current_step', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_steps', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('trigger', sa.VARCHAR(length=20), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['user_workflows.workflow_id'], name='fk_workflow_runs_workflow_id'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('conversation_messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'complete'"), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], name='fk_conv_messages_conversation_id'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('workflow_steps',
    sa.Column('step_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('artifacts', sa.JSON(), nullable=True),
    sa.Column('llm_tokens_used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.run_id'], name='fk_workflow_steps_run_id'),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_table('workflow_artifacts',
    sa.Column('artifact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(), nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('file_size', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.VARCHAR(), server_default=sa.text("''"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.run_id'], name='fk_workflow_artifacts_run_id'),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.step_id'], name='fk_workflow_artifacts_step_id'),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_artifacts')
    op.drop_table('workflow_steps')
    op.drop_table('conversation_messages')
    op.drop_table('workflow_runs')
    op.drop_table('conversations')
    op.drop_table('user_workflows')
    op.drop_table('group_settings')
    op.drop_index(op.f('ix_api_users_email'), table_name='api_users')
    op.drop_index(op.f('ix_api_users_deleted'), table_name='api_users')
    op.drop_table('api_users')
    op.drop_table('workflow_types')
    op.drop_table('api_settings')
    op.drop_index(op.f('ix_api_groups_deleted'), table_name='api_groups')
    op.drop_table('api_groups')
    # ### end Alembic commands ###
